

module.exports = {
    "eng": function gen(){
        return {
            subject: "Welcome to Axiom!",
            header_thank_you: "English Thank you!",
            header_subtitle: "We have added your email address to the signup queue.",
            ahead_text: "354,156 People are ahead of you",
            ahead_subtext: "This reservation is held for email@example.com, is this not you?",
            rewarded_text: "Get rewarded",
            rewarded_subtext: "Get early access and commmission by referring your friends. The more friends that join, the sooner you'll get access and the more commission you'll earn per trade when we go live.",
            people_referred: "people referred",
            percent_of_commission: "% of commmissions",
            first_tier: "100 or more",
            first_tier_percent: "10%",
            second_tier: "500 or more",
            second_tier_percent: "15%",
            third_tier: "1000 or more",
            third_tier_percent: "20%",
            share_this_link: "Or share this unique link",
            user_referral_link: "https://www.example.com/?ref=difohsodfisdnfiosdfnaosi",
            monitor_your_progress: "Monitor your progress",
        }
    },
    "span": function gen(){
        return {
            subject: "Bienvenido a Axiom!",
            header_thank_you: "Gracias!",
            header_subtitle: "We have added your email address to the signup queue.",
            ahead_text: "354,156 People are ahead of you",
            ahead_subtext: "This reservation is held for email@example.com, is this not you?",
            rewarded_text: "Get rewarded",
            rewarded_subtext: "Get early access and commmission by referring your friends. The more friends that join, the sooner you'll get access and the more commission you'll earn per trade when we go live.",
            people_referred: "people referred",
            percent_of_commission: "% of commmissions",
            first_tier: "100 or more",
            first_tier_percent: "10%",
            second_tier: "500 or more",
            second_tier_percent: "15%",
            third_tier: "1000 or more",
            third_tier_percent: "20%",
            share_this_link: "Or share this unique link",
            user_referral_link: "https://www.example.com/?ref=difohsodfisdnfiosdfnaosi",
            monitor_your_progress: "Monitor your progress",
        }
    },
    "rus": function gen(){
        return {
            subject: "Welcome to Axiom!",
            header_thank_you: "Russian Thank you!",
            header_subtitle: "We have added your email address to the signup queue.",
            ahead_text: "354,156 People are ahead of you",
            ahead_subtext: "This reservation is held for email@example.com, is this not you?",
            rewarded_text: "Get rewarded",
            rewarded_subtext: "Get early access and commmission by referring your friends. The more friends that join, the sooner you'll get access and the more commission you'll earn per trade when we go live.",
            people_referred: "people referred",
            percent_of_commission: "% of commmissions",
            first_tier: "100 or more",
            first_tier_percent: "10%",
            second_tier: "500 or more",
            second_tier_percent: "15%",
            third_tier: "1000 or more",
            third_tier_percent: "20%",
            share_this_link: "Or share this unique link",
            user_referral_link: "https://www.example.com/?ref=difohsodfisdnfiosdfnaosi",
            monitor_your_progress: "Monitor your progress",
        }
    },
    "mand": function gen(){
        return {
            subject: "Welcome to Axiom!",
            header_thank_you: "Mandarin Thank you!",
            header_subtitle: "We have added your email address to the signup queue.",
            ahead_text: "354,156 People are ahead of you",
            ahead_subtext: "This reservation is held for email@example.com, is this not you?",
            rewarded_text: "Get rewarded",
            rewarded_subtext: "Get early access and commmission by referring your friends. The more friends that join, the sooner you'll get access and the more commission you'll earn per trade when we go live.",
            people_referred: "people referred",
            percent_of_commission: "% of commmissions",
            first_tier: "100 or more",
            first_tier_percent: "10%",
            second_tier: "500 or more",
            second_tier_percent: "15%",
            third_tier: "1000 or more",
            third_tier_percent: "20%",
            share_this_link: "Or share this unique link",
            user_referral_link: "https://www.example.com/?ref=difohsodfisdnfiosdfnaosi",
            monitor_your_progress: "Monitor your progress",
        }
    },
    "port": function gen(){
        return {
            subject: "Welcome to Axiom!",
            header_thank_you: "Portuguese Thank you!",
            header_subtitle: "We have added your email address to the signup queue.",
            ahead_text: "354,156 People are ahead of you",
            ahead_subtext: "This reservation is held for email@example.com, is this not you?",
            rewarded_text: "Get rewarded",
            rewarded_subtext: "Get early access and commmission by referring your friends. The more friends that join, the sooner you'll get access and the more commission you'll earn per trade when we go live.",
            people_referred: "people referred",
            percent_of_commission: "% of commmissions",
            first_tier: "100 or more",
            first_tier_percent: "10%",
            second_tier: "500 or more",
            second_tier_percent: "15%",
            third_tier: "1000 or more",
            third_tier_percent: "20%",
            share_this_link: "Or share this unique link",
            user_referral_link: "https://www.example.com/?ref=difohsodfisdnfiosdfnaosi",
            monitor_your_progress: "Monitor your progress",
        }
    },

}